### ISSUE TITLE
Inconsistent kerning of pairs ending with a comma

### ISSUE THREAD

**Issue by baskerville** [notofonts/latin-greek-cyrillic#155]
![noto-comma_kerning](https://user-images.githubusercontent.com/159419/33942019-e4495486-e014-11e7-8ef4-4ade098bfe38.png)

The font used is *NotoSerif-Italic* but the problem seems to exist in every variant.

**Comment by simoncozens** [comment]
I think this is fixed now, although things are the same as when nizarsq tested - unless I'm missing something, the problem was that there was a gap between r and comma; now there isn't, so we're good?

![shape](https://user-images.githubusercontent.com/106728/216607270-e21825ab-0bcc-4788-bdaa-6b3870f54263.png)
