### ISSUE TITLE
Noto Sans and Noto Sans Bold have differ size while setted as 13 px

### ISSUE THREAD

**Issue by sutnistj** [notofonts/latin-greek-cyrillic#2]
### Font 
- Noto Sans
- Noto Sans Bold

Both are hinted TTF. Maybe problem is not only with those fonts.

<details>
  <summary>Pictures</summary>

![image](https://user-images.githubusercontent.com/8969612/170219086-57ae7207-fad9-4085-8002-8cd71f760c2d.png)

</details>

### Where the font came from, and when
From [here](https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf), I use git version which linked to `/usr/share/fonts/truetype`. 
  >   Date: 2022-05-25 (preferred format)

### Font Version
  > * Linux -- use (Gnome) Font Viewer: open a font and click on Info tab.

<details>
  <summary>Pictures</summary>

![image](https://user-images.githubusercontent.com/8969612/170216471-e713b199-d929-42dc-a4c5-d9bdd39c2011.png)
![image](https://user-images.githubusercontent.com/8969612/170216968-0f55d876-7a04-481b-a56d-a9959cb36d95.png)

</details>

### OS name and version
  > This is especially important if the font came pre-installed.

I installed. 

> OS: Linux Mint 20.3 x86_64

### Application name and version
  > Google Chrome 101.0.4951.64

### Issue
  > Noto Sans and Noto Sans Bold have differ size while setted as 13 px

<details>
  <summary>Pictures</summary>

13px
![image](https://user-images.githubusercontent.com/8969612/170217538-31e53fa0-f98d-43fd-ab43-af7b4b73ff43.png)

For compare: 14px
![image](https://user-images.githubusercontent.com/8969612/170218565-7095b200-ec0c-4d28-befb-a2ee3595a3f6.png)

And: 12px
![image](https://user-images.githubusercontent.com/8969612/170218284-68b9747d-3c29-4529-aa6a-27bdfa35efaa.png)

Serif: 13px 
![image](https://user-images.githubusercontent.com/8969612/170220708-813eb27e-f7dd-4531-bc93-6c57ea72c8b4.png)

</details>

**Comment by simoncozens** [comment]
I'm not sure what to do with this; I don't think it's a problem with the fonts - if anything it's a problem with the freetype renderer. (For example, the fonts render fine on OSX: 
<img width="447" alt="Screenshot 2023-01-19 at 12 07 54" src="https://user-images.githubusercontent.com/106728/213439121-d32cc93f-f164-4415-a776-2fd0c8214c60.png">
but I suspect that is ignoring the hints.)

Could you try a few things for me?

1) Check with the latest versions from https://notofonts.github.io/latin-greek-cyrillic/
2) Check with the unhinted version instead of the hinted version.
3) Check with the variable font.
