### ISSUE TITLE
Some fonts might need update for USE and default mark zeroing behavior change in HB

### ISSUE THREAD

**Issue by behdad** [notofonts/latin-greek-cyrillic#230]
In HarfBuzz 1.2.0 I change Universal Shaping Engine mark zeroing behavior to match (undocumented) Microsoft behavior:

  https://github.com/behdad/harfbuzz/commit/da41e48f0a1a6af6d44ef25185d2421a29bd4166

We should go over those of noto-fonts that go through USE and double-check that they behave correctly after this change.  If the fonts were tested against Windows, they should work better with HB now.  If, on the other hand, they were built against HB, we might need to hotpatch them to add the width of marks back in 'dist' GPOS feature.

**Comment by simoncozens** [comment]
I'm not sure what we're supposed to be checking for, but the rhotic hooks look fine (they're implemented as spacing base characters instead of marks anyway):

![shape](https://user-images.githubusercontent.com/106728/213484818-9f0ae439-90a2-4dc1-b3fb-510fbeb0d4e0.png)
![shape](https://user-images.githubusercontent.com/106728/213484918-ffa683cb-f92c-4223-a190-85b1c008d798.png)
