### ISSUE TITLE
Noto Sans Regular shows as Thin Condensed upon installation

### ISSUE THREAD

**Issue by berrymot** [notofonts/latin-greek-cyrillic#429]
### Title 
Noto Sans Regular shows as Thin Condensed upon installation

### Font 
NotoSans-Regular.ttf

### Where the font came from, and when
Downloaded directly from the `gh-pages` branch in `fonts/NotoSans/hinted/ttf/` on 2023-05-25 ~18:44 PDT.

### Font Version
Noto Sans 2.012

### OS name and version
Windows 11

### Issue
The install window shows the name as Noto Sans Regular, but Settings says it's Thin Condensed. When the italic version is subsequently installed, everything that should be in Regular is in Italic.

### Screenshots
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/50974538/59a2650b-8a50-4c3c-922f-9898cbbfeb27)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/50974538/d53fc2f8-0c5c-4710-9a26-69e56d32e060)

**Comment by simoncozens** [comment]
This is really interesting; it's probably related to #227. I'm really struggling to understand both these issues - we build this font with the same tools as all our others, and it conforms to the QA standards in the Google Fonts Guide, so if there is a problem with how Windows handles this kind of font then we're currently not catching it with our QA tools - and I don't have Windows to debug it.

But it's useful to see that it's happening in a static font, because the only place that "Thin Condensed" is mentioned is in the STAT table. And "Thin"/"Condensed" are the first values for each axis in that STAT table. Unfortunately I'm not really familiar enough with how STAT tables are used to diagnose the problem further, but I'll ask around.

**Comment by simoncozens** [comment]
I think I've found the problem. Please try again when the [current build](https://github.com/notofonts/latin-greek-cyrillic/actions/runs/5088601364) completes (roughly an hour from now).

**Comment by berrymot** [comment]
I installed the variable fonts from notofonts.github.io shortly after opening this issue lol, but will do

**Comment by berrymot** [comment]
Worked! :>
