### ISSUE TITLE
Roman Numerals?

### ISSUE THREAD

**Issue by curya** [notofonts/latin-greek-cyrillic#440]
I wasn't sure where to post this but I just discovered that Roman numerals are not a part of Noto Sans Latin/Greek/Cyrillic and maybe they should be?

Apparently they're in Noto Sans Symbols. But only sans. No serif?

Are there plans to include Roman numerals in Noto Sans Latin/Greek/Cyrillic? And making a serif version of them?

**Comment by bsoap-cat** [comment]
There's also no dozenal digits in Noto Sans which is also present in Noto Sans Symbols which is upsetting as someone who is interested in dozenal

**Comment by simoncozens** [comment]
We won't be including roman numerals or dozenal digits in Noto Sans LGC because they're already covered in Symbols. Noto Sans is not expected to be a single font to cover all codepoints, but instead it's part of the Noto system; you can always use the two fonts together as part of a font fallback stack. Otherwise there's simply no end to the codepoints we could add.

I don't think there are any pans to make serif versions of Roman numerals, no.
