### ISSUE TITLE
Noto latin font not working correctly with tilde diacritic below?

### ISSUE THREAD

**Issue by lancejpollard** [notofonts/latin-greek-cyrillic#447]
Here is my project, notice the word `nẏa̰no̰ntaq` has tildes below the a and o, it doesn't show up correctly in my web app using Google's hosted Noto Sans. Am I doing something wrong?

![2023-10-06 12 38 48](https://github.com/notofonts/latin-greek-cyrillic/assets/28718/1ecb1a1a-bdeb-4c28-8779-8a93a70f3c01)

```
https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@400%3B700&family=Noto+Sans+Armenian:wght@400%3B700&family=Noto+Sans+Bengali:wght@400%3B700&family=Noto+Sans+Canadian+Aboriginal:wght@400%3B700&family=Noto+Sans+Cuneiform&family=Noto+Sans+Devanagari:wght@400%3B700&family=Noto+Sans+Egyptian+Hieroglyphs&family=Noto+Sans+Ethiopic:wght@400%3B700&family=Noto+Sans+Georgian:wght@400%3B700&family=Noto+Sans+Gujarati:wght@400%3B700&family=Noto+Sans+Gurmukhi:wght@400%3B700&family=Noto+Sans+Hebrew:wght@400%3B700&family=Noto+Sans+JP:wght@400%3B700&family=Noto+Sans+KR:wght@400%3B700&family=Noto+Sans+Kannada:wght@400%3B700&family=Noto+Sans+Khmer:wght@400%3B700&family=Noto+Sans+Malayalam:wght@400%3B700&family=Noto+Sans:wght@400%3B700&family=Noto+Sans+Mono:wght@400%3B700&family=Noto+Sans+Oriya:wght@400%3B700&family=Noto+Sans+Runic&family=Noto+Sans+SC:wght@400%3B700&family=Noto+Sans+Sinhala:wght@400%3B700&family=Noto+Sans+Syriac&family=Noto+Sans+Tamil:wght@400%3B700&family=Noto+Sans+Telugu:wght@400%3B700&family=Noto+Sans+Thai:wght@400%3B700&family=Noto+Serif+Tibetan:wght@400%3B700&display=swap
```

**Comment by simoncozens** [comment]
You're not doing anything wrong, and there's nothing wrong with the font either:
![shape](https://github.com/notofonts/latin-greek-cyrillic/assets/106728/10558579-6571-49cb-afb8-6ae265b5c2ce)

The problem is that Google Font's API is splitting the font into multiple subsets, and these do not correctly recombine to put the tilde under the vowels.

**Comment by moyogo** [comment]
You should likely self-host the full font or a subset of it that meets your requirements.

**Comment by moyogo** [comment]
You can also specify what subset you want with Googlw Fonts by providing the text characters you need: https://developers.google.com/fonts/docs/getting_started#optimizing_your_font_requests

**Comment by lancejpollard** [comment]
Can you explain further what you mean by the subset thing?

It's curious too, I realize it's not working on localhost (using the remote google font system), but it _is_ working in production, so not sure what the difference is.

**Comment by simoncozens** [comment]
> Can you explain further what you mean by the subset thing?

When a font is served using the Google Fonts web API (i.e. you have something in your HTML like `<link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet">` or whatever) then it is actually split into several different fonts based on a set of Unicode codepoints, and these split fonts are delivered to your browser. So you effectively get Noto Sans 1, Noto Sans 2, etc; these separate fonts are used for different codepoints. This is done so that you don't end up will all of Noto Sans' 1000+ characters if you're just setting basic Latin text. It saves bandwidth for you and for Google.

Unfortunately, for reasons best understood by the engineering team, the letter "a" ends up in Noto Sans 1 and the "combining tilde below" ends up in Noto Sans 2, and the browser can't do mark attachment between two different fonts, which is why the tilde does not get correctly attached to the `a`.

I believe the eng team are working on a smarter way to deliver this, but for now this is a bug in the Google Fonts web service, which (on the Noto side) there isn't much way around - other than, as Denis mentions, hosting the font yourself.
