### ISSUE TITLE
Kerning and overlapping issues in heavier weights of Noto Serif

### ISSUE THREAD

**Issue by MAZ06** [notofonts/latin-greek-cyrillic#474]
### Font 
NotoSerif[wdth,wght].ttf

### Where the font came from, and when
https://github.com/notofonts/latin-greek-cyrillic/releases

### Font Version
Noto Serif 2.013

### OS name and version
Windows 11

### Application name and version
Everything

### Issue
I noticed a number of lowercase letter combos that have some issues. Namely:
ww
yy
fb
fh
fi (with ligatures turned off)
fk
fl (with ligatures turned off)
fv
fw
fy
vi
wi
yi
kz
qj
qw
gv
vv
vw
wv
gy
qy
yy

In this screenshot below, I show the Black weight but I'm sure at least some of the issues probably exist down to Bold. This problem probably also affects capital Latin letters as well as Greek and Cyrillic. Just wanted to post this here before I do the tedious work of the other glyphs.

I also noticed a lot of inconsistency with kerning between many letters. I know Noto Serif isn't a mono font, but shouldn't the serifs be positioned the same width apart?
For example, "mmm" has perfectly positioned width between its serifs as expected, but something like "nkn" has a wider space before the k and a smaller space after the k. If this a real issue, then it likely affects all weights.

### Screenshot
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/1719d0dd-6ca6-4d7e-b070-c586e8005abd)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/df7f2778-1309-40a5-a759-7f47d5cd5902)
![image](https://github.com/notofonts/latin-greek-cyrillic/assets/165231781/c3b35e98-bdac-4a11-974c-f64b959d8395)

**Comment by simoncozens** [comment]
> I know Noto Serif isn't a mono font, but shouldn't the serifs be positioned the same width apart?

I'll take a look at the details of this font soon, but in general, no, that's not how spacing works. Looking at the overall glyph shape, in and particular the rhythm of *stems* is more important than the ink-to-ink distance to create a rhythmic pattern of text. (If kerning was just a matter of making serifs equal width apart we could very easily kern automatically. ) I suspect what is happening in many of these examples is that there is apparent overlap so that the stem rhythm can be maintained. See for example [Frank Blokland's work on letter models](https://typedrawers.com/discussion/749/the-lemo-method/p1); he explains how serifs can be made inconsistent so that stem rhythm can be made consistent.

**Comment by simoncozens** [comment]
I'm going to close this, because having looked at the design, I think it's fine. Latin glyphs can overlap to maintain good stem rhythm, and that is what's happening here.
